# Escape-time to avoid conflicts with NeoVim
set-option -sg escape-time 10

# VIM bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -r -T prefix C-k resize-pane -U
bind-key -r -T prefix C-j resize-pane -D
bind-key -r -T prefix C-h resize-pane -L
bind-key -r -T prefix C-l resize-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Theme
source-file ~/.config/tmux/theme.conf

# reload config file
bind r source-file ~/.config/tmux/tmux.conf

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
