#   ___
#  / _ \ _ __   ___  ___   Mario Dominguez 
# | | | | '_ \ / _ \/ __|  https://gitlab.com/opeshm
# | |_| | |_) |  __/\__ \  https://github.com/opeshm
#  \___/| .__/ \___||___/  https://opeshm.gitlab.io/
#       |_|
#
# Picom documentation: https://github.com/yshui/picom
# 

shadow = true;
shadow-radius = 8;
shadow-opacity = .6
