# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

source = ~/.config/hypr/hyprland-monitors.conf
source = ~/.config/hypr/hyprland-programs.conf
source = ~/.config/hypr/hyprland-autostart.conf
source = ~/.config/hypr/hyprland-env-vars.conf
source = ~/.config/hypr/hyprland-inputs.conf
source = ~/.config/hypr/hyprland-permissions.conf
source = ~/.config/hypr/hyprland-lookandfeel.conf
source = ~/.config/hypr/hyprland-keybinding.conf
source = ~/.config/hypr/hyprland-windows.conf

# Override Setttings
source = UserConfigs/**.conf
