#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
exec-once = /usr/lib/pam_kwallet_init
exec-once = nm-applet &
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar & hyprpaper
exec-once = swaync
exec-once = $HOME/.config/hypr/startup.sh
