# See https://wiki.hypr.land/Configuring/Monitors/
# monitor = name, resolution, position, scale
## There are a few special values for the resolutions:
## * preferred - use the display’s preferred size and refresh rate.
## * highres - use the highest supported resolution.
## * highrr - use the highest supported refresh rate.
## * maxwidth - use the widest supported resolution.

## Position also has a few special values:
## * auto - let Hyprland decide on a position. By default, it places each new monitor to the right of existing ones, using the monitor’s top left corner as the root point.
## * auto-right/left/up/down - place the monitor to the right/left, above or below other monitors, also based on each monitor’s top left corner as the root.
## * auto-center-right/left/up/down - place the monitor to the right/left, above or below other monitors, but calculate placement from each monitor’s center rather than its top left corner.

# monitor=,preferred,auto,auto
monitor=HDMI-A-1,preferred,auto-right,1
monitor=HDMI-A-2,preferred,auto-left,1,transform,1
